"""agent session tenant binding

เพิ่มคอลัมน์ tenant_id (nullable) ให้ agent_sessions — session ที่มีอยู่เดิมได้ NULL
คือ "ไม่ผูก tenant" ซึ่งเป็นพฤติกรรมเดิมเป๊ะ ไม่ต้อง backfill

batch_alter_table ใช้ได้ทั้ง sqlite และ postgres (บน PG จะออกเป็น ALTER TABLE ปกติ)

Revision ID: e53fb8ec8212
Revises: 12e243579759
Create Date: 2026-08-20 16:13:08.246501
"""
from alembic import op
import sqlalchemy as sa


revision = 'e53fb8ec8212'
down_revision = '12e243579759'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tenant_id', sa.String(length=63), nullable=True))
        batch_op.create_index(batch_op.f('ix_agent_sessions_tenant_id'), ['tenant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_tenant_id'))
        batch_op.drop_column('tenant_id')

    # ### end Alembic commands ###
