"""initial schema

Revision ID: 93fdf03d219e
Revises: 
Create Date: 2026-08-07 14:11:27.109097
"""
from alembic import op
import sqlalchemy as sa


revision = '93fdf03d219e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('channel_secret', sa.String(length=128), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('agent_enabled', sa.Boolean(), nullable=False),
    sa.Column('greeting', sa.Text(), nullable=False),
    sa.Column('quick_menu', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('line_link_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('line_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_pk', sa.Integer(), nullable=False),
    sa.Column('line_user_id', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('agent_session_id', sa.Integer(), nullable=True),
    sa.Column('followed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_session_id'], ['agent_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_pk'], ['line_channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_pk', 'line_user_id')
    )
    with op.batch_alter_table('line_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_line_users_channel_pk'), ['channel_pk'], unique=False)
        batch_op.create_index(batch_op.f('ix_line_users_line_user_id'), ['line_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('line_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_line_users_line_user_id'))
        batch_op.drop_index(batch_op.f('ix_line_users_channel_pk'))

    op.drop_table('line_users')
    op.drop_table('line_link_codes')
    op.drop_table('line_channels')
    # ### end Alembic commands ###
